variable "aws_region" {
  description = "Region for the whole stack. ap-south-1 is Mumbai, close to this machine. Change it before apply if you want another region."
  type        = string
  default     = "ap-south-1"
}

variable "project_name" {
  description = "Short name used in resource names and tags."
  type        = string
  default     = "assettracker"
}

variable "environment" {
  description = "Environment label. This stack is sized for practice, so the default is dev."
  type        = string
  default     = "dev"
}

variable "vpc_cidr" {
  description = "Address range for the VPC. /16 leaves room for more subnets later."
  type        = string
  default     = "10.20.0.0/16"
}

variable "github_repository" {
  description = "GitHub repository in owner/name form. CodePipeline reads this through a CodeConnections connection."
  type        = string
  default     = "RaviKantGautam/assettracker"

  validation {
    condition     = can(regex("^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$", var.github_repository))
    error_message = "github_repository must look like owner/name, for example RaviKantGautam/assettracker."
  }
}

variable "github_branch" {
  description = "Branch that triggers the pipeline. The assettracker repository uses master."
  type        = string
  default     = "master"
}

variable "container_port" {
  description = "Port gunicorn listens on inside the container. The local docker-compose file publishes Django on 8000, so the task uses the same port."
  type        = number
  default     = 8000
}

variable "desired_count" {
  description = "How many Django tasks to keep running. One task is enough for practice and avoids two containers racing on migrate."
  type        = number
  default     = 1
}

variable "fargate_cpu" {
  description = "Task CPU units. 512 is 0.5 vCPU, the small practice size for a Django process."
  type        = number
  default     = 512
}

variable "fargate_memory" {
  description = "Task memory in MiB. 1024 matches 0.5 vCPU on the Fargate size table."
  type        = number
  default     = 1024
}

variable "db_name" {
  description = "MySQL schema created on the RDS instance. Django's DATABASE_URL points at this name."
  type        = string
  default     = "assettracker"
}

variable "db_username" {
  description = "Master username for RDS. The password is generated by Terraform and stored in Secrets Manager."
  type        = string
  default     = "assettracker"
}

variable "db_instance_class" {
  description = "RDS instance size. db.t4g.micro is the smallest Graviton size and is enough for a practice schema."
  type        = string
  default     = "db.t4g.micro"
}
